apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mongo-db-creds
  namespace: solar-system
spec:
  encryptedData:
    MONGO_URI: AgAIFsbYrrP296i1okFLoS4F7x6gXqIsIWePd8Bo2LW+EF3d0srjgABdYMhdwnGK9U12wFccYvbfq3y6+eAnnE3n37pQv0Jd5k0tSM+jUN/5SbUintdh3YVuLopFgFy3JbO51b06kY14OsD/HSMBPpPNxYxA3HwYwBTaYGa8CX17AUq34NVyjN8zBVgRDcjeLnt/WV0yiLxXiuY5kiZMG1VcD858HQSd7TDsw8Brs6gvjPDan8+rv/uQUHFMbfMH1GKm7ltQj2WnM3Y6JXVp1qJzS6i0xibMcqmTTu53yac7qjYVLZokNRhf52Jaa+NgwbQXJuo5dnVWkpg6Xkqo1tMWxnCHXfRTT5Y9ws7Zn7PqIklP8ueNjFilb4OaBVqjmYC44TT5OUvM7U/AdfqLFvW0/pTN+z8hTHPOECKAntP+FcHRZhKGN31va2KI5BCa3dzwxRzXgWu/3296/H7tcaiWz0g4FvHP1WnXIse/Lq4jw7f6swjSrHR7kN3szebmaZjWEF+GqqTmIOGE4Yo929PkHfq28i07MGDsUqLwN805JaTA307pR/TDR+wtO/xxixm/0KSlc58EACCUTJeRiY102zogPRcdrgrBH++Tl25pQC6LKxJteK9bHNK7Yyn9vvQlKia0e011yqFskABvvA++KD1HkXu8XnFQwEBGkDMcHQwrXcdmLpJBdL9x/omX+bnP/jR4J9yta6Fhazieth49TMD6dVTtF6K2sFABF7h6LBmbpnLNPWnp0R0RuVVq2cIz55RaO/c/3DzS2cwdWmfZXGHTH5vkQ4HVn6F5BgU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mongo-db-creds
      namespace: solar-system

