apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - secret.yml

images:
  - name: solar-system-app
    newTag: 49c968df9b358b555d43126dc006156b2fdf51a2