apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - secret.yml

images:
- name: ${ECR_HOST_URL}/pvaddocker/solar-system
  newName: placeholder-for-argocd
  newTag: latest