apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - secret.yml

images:
  - name: pvaddocker/solar-system
    newTag: e371d1908b84b8d558884c0d014c2b43091863a5